table dim_date
	lineageTag: 412acda0-5f31-4d2e-aa73-91031551d02b

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 7938d3de-5846-4a18-b982-53d1a8a1d87c
		summarizeBy: sum
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: aeab11ba-174a-4763-aad3-92baf30c90e0
		summarizeBy: none
		sourceColumn: full_date

		variation Variation
			isDefault
			relationship: c7bc9065-175a-4365-b739-dacd8e34c82b
			defaultHierarchy: LocalDateTable_c038730f-b6b1-4f71-ae17-52725eb91319.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 25bb7ac0-6186-4808-89dc-507106cfe849
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 26a786f9-64d3-4962-9e5e-9243fa89ec09
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: da363bb2-bedf-4801-9ab7-7583f537928d
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 0172ea6d-56e3-4759-b802-f449e33270f0
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column week
		dataType: int64
		formatString: 0
		lineageTag: be2d5395-2365-4869-a6e1-326c6a82147a
		summarizeBy: sum
		sourceColumn: week

		annotation SummarizationSetBy = Automatic

	column day_of_month
		dataType: int64
		formatString: 0
		lineageTag: 72af2844-1fce-436a-8c49-5e508a039f05
		summarizeBy: sum
		sourceColumn: day_of_month

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: c1bb44e0-87b1-441b-a970-1a5ea45fd8b9
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: ca96357b-4fde-45e0-8cb9-39cc15571472
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 03b780ab-6069-4905-8308-a15fbb6da355
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 325a7967-5fc5-4d01-86fb-a54fb793d5f8
		summarizeBy: none
		sourceColumn: year_month

		variation Variation
			isDefault
			relationship: 0d980ec7-50c4-42f8-a5b8-6b8d1b506507
			defaultHierarchy: LocalDateTable_b055b850-188b-416e-a0ca-76bc0aaca197.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_date = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("E:\data\logistics-data-warehouse\logistics_dwh_gold.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "dim_date", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"date_key", Int64.Type}, {"full_date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"week", Int64.Type}, {"day_of_month", Int64.Type}, {"day_of_week", Int64.Type}, {"day_name", type text}, {"is_weekend", type logical}, {"year_month", type date}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

